apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "age-secrets.fullname" . }}-job
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "age-secrets.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "age-secrets.fullname" . }}-job
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "age-secrets.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "age-secrets.fullname" . }}-job
subjects:
  - kind: ServiceAccount
    name: {{ include "age-secrets.fullname" . }}-job
    namespace: {{ .Release.Namespace }}
